bag/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

products/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product,
         name='delete_product'),
]

urban_glam_wear/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('newsletter/', include('newsletter.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'urban_glam_wear.views.handler404'

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings
from decimal import Decimal
from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=50, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2,
                                        null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False, blank=False,
                                  default='')

    def _generate_order_number(self):
        """
        Generate a random and Unique order number using UUID
        """

        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total every time an item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total')
        )['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * Decimal(
                settings.STANDARD_DELIVERY_PERCENTAGE
            )
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """ Override the original save method to set the order number
        if it hasn't been set already
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False,
                              on_delete=models.CASCADE,
                              related_name='lineitems')
    product = models.ForeignKey(Product, null=False, blank=False,
                                on_delete=models.CASCADE)
    product_size = models.CharField(max_length=2, null=True, blank=True)
    quantity = models.IntegerField(null=True, blank=True, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2,
                                         null=False, blank=False,
                                         editable=False)

    def save(self, *args, **kwargs):
        """ Override the original save method to set the lineitem total
        and uopdate the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models
from profiles.models import UserProfile


class Category (models.Model):
    """ This model holds the category data """

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=128)
    friendly_name = models.CharField(max_length=128, null=True, blank=True)
    description = models.CharField(max_length=128, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


def custom_image_upload_to(instance, filename):
    return filename


class Product(models.Model):
    """ This model holds the product data """
    category = models.ForeignKey('Category', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    name = models.CharField(max_length=254)
    description = models.TextField()
    has_sizes = models.BooleanField(default=True, null=True, blank=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    sku = models.CharField(max_length=128, null=True, blank=True)
    carbon_footprint = models.DecimalField(max_digits=6, decimal_places=2,
                                           null=True, blank=True)
    rating = models.DecimalField(max_digits=6, decimal_places=2,
                                 null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(upload_to=custom_image_upload_to,
                              null=True, blank=True)
    user_wishlist = models.ManyToManyField(UserProfile,
                                           related_name='wishlist_products',
                                           blank=True)

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        exclude = ['user_wishlist']

    image = forms.ImageField(label='Image',
                             required=False,
                             widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_name = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_name
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-1'

products/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .models import Product, Category
from django.contrib import messages
from django.db.models.functions import Lower
from django.db.models import Q
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required

from .forms import ProductForm
from products.models import Product
from profiles.models import UserProfile


def search_products(query):
    """ A helper function to search for products based on a query """
    return Product.objects.filter(Q(name__icontains=query)
                                  | Q(description__icontains=query))


def all_products(request):
    """
    A view to show all products,
    including sorting and search queries
    """

    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None
    wishlist = []

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(
                    request, "You didn't enter any search criteria!")
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(
                description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    try:
        if request.user.is_authenticated:
            user_profile = UserProfile.objects.get(user=request.user)
            wishlist = Product.objects.filter(user_wishlist=user_profile)
    except UserProfile.DoesNotExist:
        messages.error(request, "UserProfile does not exist"
                       " for the authenticated user.")

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
        'wishlist': wishlist,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show individual product details """

    product = get_object_or_404(Product, pk=product_id)
    user_profile = None
    wishlist = []

    try:
        if request.user.is_authenticated:
            user_profile = UserProfile.objects.get(user=request.user)
            wishlist = Product.objects.filter(user_wishlist=user_profile)
    except UserProfile.DoesNotExist:
        messages.error(request, "UserProfile does not exist for"
                       " the authenticated user.")

    context = {
        'product': product,
        'wishlist': wishlist,
    }

    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """ Add a Product to the store """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, this action is allowed'
                       ' only for authorized users.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Product successfully added!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to add product. Please ensure'
                           ' all data entries are correct and valid.')
    else:
        form = ProductForm()
    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Edit a Product """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, this action is allowed'
                       ' only for authorized users.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, f'The product { product.name }'
                             ' has been updated successfully.')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, f'Failed to update product'
                           f' { product.name }. Please check all data'
                           ' entries are correct')
    else:

        form = ProductForm(instance=product)
        messages.info(request, f'You are editing { product.name }')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@csrf_protect
@login_required
def delete_product(request, product_id):
    """ Delete a product """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, this action is allowed'
                       ' only for authorized users.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product_name = product.name

    if request.method == 'POST':
        try:
            product.delete()
            messages.success(request, f'The product "{product_name}"'
                             ' has been deleted successfully.')
            print(f'Redirecting to products page... {str(e)}')
            return redirect(reverse('products'))
        except Exception as e:
            messages.error(request, f'Error deleting product'
                           f' "{product_name}": {str(e)}')

    print('Redirecting to Home page...')
    return redirect(reverse('home'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h4 class="logo-font mb-4">Product Management</h4>
                <h5 class="text-warning small">Add a Product</h5>
                <hr>
            </div>
        </div>    
        <div class="row">
            <div class="col-12 col-md-6">
                <form action="{% url 'add_product' %}" method="POST" class="form mb-4" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-right">
                        <a class="btn btn-outline-primary" href="{% url 'products' %}">Cancel</a>
                        <button class="btn btn-outline-warning" type="submit">Add Product</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h4 class="logo-font mb-4">Product Management</h4>
                <h5 class="text-warning small">Edit a Product</h5>
                <hr>
            </div>
        </div>    
        <div class="row">
            <div class="col-12 col-md-6">
                <form action="{% url 'edit_product' product.id %}" method="POST" class="form mb-4" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-right">
                        <a class="btn btn-outline-primary" href="{% url 'products' %}">Cancel</a>
                        <button class="btn btn-outline-warning" type="submit">Update Product</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="containe-fluid my-4">
        <div class="product-container col-10 offset-1 col-lg-8 offset-lg-2 pb-4">
            <div class="d-flex justify-content=center row">
                <div class="row p-2 bg-black border rounded">
                    <div class="col-12 col-md-6 col-lg-5 offset-lg-1">
                        <div class="image-container my-3">
                            {% if product.image %}
                            <a href="{{ product.image.url }}" target="_blank" class="box">
                                <img src="{{ product.image.url }}" alt="{{ product.name }}">
                            </a>
                            {% else %}
                            <a href="" class="box">
                                <img src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                            </a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-12 col-md-6 col-lg-5">
                        <h5 class="card-title text-center my-3 slogan">{{ product.name }}</h5>
                        <p class="card-text my-3">{{ product.description }}</p>
                        <p class="card-text font-weight-bold mb-0">{{ product.price }} €</p>
                        {% if product.rating %}
                        <p class="text-muted mb-0"><i class="fas fa-star mr-1" style="color:yellow;"></i> {{ product.rating }}/ 5</p>
                        {% else %}
                        <p class="text-muted mb-0">No Rating</p>
                        {% endif %}
                        {% if product.carbon_footprint %}
                        <p class="text-green mb-0"><i class="fa-solid fa-leaf" style="color: green;"></i> {{ product.carbon_footprint }}
                            CO₂ kg.</p>
                        {% else %}
                        <p class="text-green mb-0">No Carbon Footprint</p>
                        {% endif %}
                        {% if product.category %}
                        <p class="small mt-1 mb-0">
                            <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                                <i class="fas fa-tag mr-2"></i>{{ product.category.friendly_name }}
                            </a>
                        </p>
                        {% endif %}
                        <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-12">
                                    <p><strong>Size:</strong></p>
                                    <select class="form-control rounded w-50" name="product_size" id='id_product_size'>
                                        <option value="xs">XS</option>
                                        <option value="s">S</option>
                                        <option value="m" selected>M</option>
                                        <option value="l">L</option>
                                        <option value="xl">XL</option>
                                    </select>
                                </div>
                                <div class="col-12">
                                    <p class="mt-3"><strong>Quantity:</strong></p>
                                    <div class="form-group w-50">
                                        <div class="input-group">
                                            <input class="form-control qty_input" type="number"
                                                name="quantity" value="1" min="1" max="99"
                                                data-item_id="{{ product.id }}"
                                                id="id_qty_{{ product.id }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 text-center">
                                    {% if user.is_authenticated %}
                                        {% if product in wishlist %}
                                            <a class="btn btn-outline-primary mt-2" role="button" href="{% url 'add_to_wishlist' product.id %}">Remove from Wishlist</a>
                                        {% else %}
                                            <a class="btn btn-outline-primary mt-2" role="button" href="{% url 'add_to_wishlist' product.id %}">Add to Wishlist</a>
                                        {% endif %}
                                    {% endif %}
                                </div>
                                <div class="col-12 text-center">
                                    <a href="{% url 'products' %}" class="btn btn-outline-info btn-sm mt-2">
                                        <span class="icon-b">
                                            <i class="fas fa-chevron-left"></i>
                                        </span>
                                        <span class="text-uppercase">Keep Shopping</span>
                                    </a>
                                    <input type="submit" class="btn btn-outline-primary btn-sm mt-2" value="Add to Bag">
                                    <input type="hidden" name="redirect_url" value="{{ request.path }}">
                                </div>
                            </div>
                        </form>
                        <div class="col-12">
                            {% if request.user.is_superuser %}
                                <a class="mt-2 btn btn-sm btn-outline-info" href="{% url 'edit_product' product.id %}"><small class="p-2" >Edit</small></a>
                                <button class="mt-2 btn btn-sm btn-outline-danger float-right" onclick="openCustomConfirm('{{ product.id }}', '{{ product.name }}')" data-toggle="modal" data-target="#customConfirmModal">Delete</button>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>    
        </div> 
    </div> 
{% endblock %}